name: Deploy VM Azure

on:
  push:
    branches:
      - main
    #paths:
      #-'carpeta/**' Se ejecuta solo si se modifica algo en el codigo dentro de esa carpeta 

jobs:
  Deploy-VM:
    name: Despliega VM en Azure
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    steps:
      # Paso 1: Chequea el código del repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Instala Terraform
      #- name: Setup Terraform
        #uses: hashicorp/setup-terraform@v2
        #with:
          #terraform_version: latest  # O puedes especificar una versión, por ejemplo: 1.5.0

      # Paso 3: Ejecuta terraform version
      - name: Run Terraform Init
        run: terraform init -backend-config="sas_token=${{ secrets.SAS_TOKEN }}"
      - name: Run Terraform FMT
        run: terraform fmt
      - name: Run Terraform Validate
        run: terraform validate
      - name: Run Terraform Plan
        run: terraform plan -var-file terraform.tfvars -out=plan.out
